name: Snapshots

on:
  # Manual Trigger GH CLI -> gh workflow run snapshots.yml --ref <tag>
  workflow_dispatch:

# Avoid duplicate workflows on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cypress-update-snapshots
  cancel-in-progress: true

jobs:
  snapshots:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash --login -eo pipefail {0}

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false
          submodules: 'recursive'